apiVersion: v1
kind: ReplicationController
metadata:
    name: haskellorg
    labels:
        name: haskellorg
spec:
  replicas: 1
  selector:
    name: haskellorg
  template:
    metadata:
        labels:
            name: haskellorg
    spec:
        containers:
        - name: haskellorg
          image: snoyberg/haskellorg
          imagePullPolicy: Always
          command: ["hl"]
          workingDir: /app
          ports:
          - containerPort: 3001
            hostPort: 3001
          env:
          - name: PORT
            value: "3001"
          livenessProbe:
              httpGet:
                  path: /
                  port: 3001
